### ISSUE TITLE
V2B 配置 的Hy 无法启动.

### ISSUE THREAD

**Issue by ClashUS** [InazumaV/V2bX#11]
**描述该错误**
启动报错
**复现**

V2bX start 

**环境和版本**
Debian 11  x86  V2b 1.7.4 hy 一键脚本
V2bX
**日志和错误**
![image](https://github.com/InazumaV/V2bX/assets/128655994/198a5695-55c0-4765-9bf2-a51f4024c3d0)
```

Aug 08 15:22:06 JP31N systemd[1]: Started V2bX Service.
Aug 08 15:22:07 JP31N V2bX[14543]: V2bX v2.0.4 (A V2board backend based on multi core)
Aug 08 15:22:07 JP31N V2bX[14543]: Supported cores: hy, xray
Aug 08 15:22:07 JP31N V2bX[14543]: This version need V2board version >= 1.7.0.
Aug 08 15:22:07 JP31N V2bX[14543]: The version have many changed for config, please check your config file
Aug 08 15:22:07 JP31N V2bX[14543]: time="2023-08-08T15:22:07+08:00" level=info msg="Start V2bX..."
Aug 08 15:22:07 JP31N V2bX[14543]: time="2023-08-08T15:22:07+08:00" level=fatal msg="Failed to parse the resolve preference" error="invalid preference: udp://8.8.8.8:53"
Aug 08 15:22:07 JP31N systemd[1]: V2bX.service: Main process exited, code=exited, status=1/FAILURE
Aug 08 15:22:07 JP31N systemd[1]: V2bX.service: Failed with result 'exit-code'.
```

**额外的内容**
config.yml
```yml
CoreConfig:
  Type: "hy"
  XrayConfig:
    Log:
      Level: warning # Log level: none, error, warning, info, debug
      AccessPath: # /etc/XrayR/access.Log
      ErrorPath: # /etc/XrayR/error.log
    DnsConfigPath: # /etc/XrayR/dns.json # Path to dns config, check https://xtls.github.io/config/dns.html for help
    RouteConfigPath: # /etc/XrayR/route.json # Path to route config, check https://xtls.github.io/config/routing.html for help
    InboundConfigPath: # /etc/XrayR/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
    OutboundConfigPath: # /etc/XrayR/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help
    ConnectionConfig:
      Handshake: 4 # Handshake time limit, Second
      ConnIdle: 30 # Connection idle time limit, Second
      UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
      DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
      BufferSize: 64 # The internal cache size of each connection, kB
Nodes:
 -
    PanelType: "NewV2board" # Panel type: SSpanel, V2board, NewV2board, PMpanel, Proxypanel, V2RaySocks
    ApiConfig:
      ApiHost: "https://p.baidu.com" 
      ApiKey: "123.12321312312"
      NodeID: 1  
      NodeType: hysteria # Node type: V2ray, Shadowsocks, Trojan
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings
      DeviceLimit: 0 # Local settings will replace remote settings
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      UpdatePeriodic: 10 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      # XrayOptions:
      #   EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      #   DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      #   EnableTFO: false # Enable TCP Fast Open
      #   EnableProxyProtocol: false # Only works for WebSocket and TCP
      #   EnableFallback: false # Only support for Trojan and Vless
      #   FallBackConfigs: # Support multiple fallbacks
      #     - SNI: # TLS SNI(Server Name Indication), Empty for any
      #       Alpn: # Alpn, Empty for any
      #       Path: # HTTP PATH, Empty for any
      #       Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
      #       ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
      HyOptions:
        Resolver: "udp://8.8.8.8:53" # DNS resolver address
        ResolvePreference: "4" # DNS IPv4/IPv6 preference. Available options: "64" (IPv6 first, fallback to IPv4), "46" (IPv4 first, fallback to IPv6), "6" (IPv6 only), "4" (IPv4 only)
        SendDevice: "eth0" # Bind device for outbound connections (usually requires root)
      CertConfig:
        CertMode: http # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "11.baidu.com" #  Domain to cert #<▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️▪️
        CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: /etc/XrayR/cert/node1.test.com.key
        Provider: cloudflare # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: baidu@gmail.com

```
